# Generated by Django 4.2.24 on 2025-09-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_companydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Job_Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Job_Role', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=100, null=True)),
                ('Job_Type', models.TextField(blank=True, max_length=100, null=True)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('Job_Date', models.DateField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
