# Generated by Django 4.2.24 on 2025-09-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=150, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('Education', models.CharField(blank=True, max_length=150, null=True)),
                ('Experience', models.IntegerField(blank=True, null=True)),
                ('Skills', models.TextField(blank=True, null=True)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('Company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('Job_role', models.CharField(blank=True, max_length=150, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
